name: '566'
channels:
  - conda-forge
  - defaults
dependencies:
  - ca-certificates=2024.9.24
  - libffi=3.4.4
  - openssl=3.0.15
  - python=3.8.20
  - sqlite=3.45.3
  - pip
  - pip:
      - asttokens==2.4.1
      - audioread==3.0.1
      - backcall==0.2.0
      - backports-functools-lru-cache==2.0.0
      - bleach==6.0.0
      - certifi==2024.8.30
      - cffi==1.15.1
      - charset-normalizer==3.4.0
      - click==8.1.7
      - colorama==0.4.6
      - comm==0.1.4
      - cycler==0.11.0
      - debugpy==1.6.3
      - decorator==5.1.1
      - docker-pycreds==0.4.0
      - entrypoints==0.4
      - executing==2.1.0
      - fonttools==4.38.0
      - ftfy==6.1.1
      - gitdb==4.0.11
      - gitpython==3.1.43
      - idna==3.10
      - importlib-metadata==6.7.0
      - importlib-resources==5.12.0
      - ipykernel==6.16.2
      - ipython==7.33.0
      - ipywidgets==8.1.5
      - jedi==0.19.1
      - joblib==1.3.2
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jupyter-client==7.4.9
      - jupyter-core==4.11.1
      - jupyterlab-widgets==3.0.13
      - kaggle==1.6.17
      - kagglehub==0.2.9
      - kiwisolver==1.4.5
      - librosa==0.7.2
      - llvmlite==0.31.0
      - matplotlib==3.5.3
      - matplotlib-inline==0.1.7
      - nest-asyncio==1.6.0
      - numba==0.48.0
      - numpy==1.18.1
      - packaging==23.2
      - pandas==1.0.3
      - parso==0.8.4
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==9.5.0
      - pip==24.0
      - platformdirs==4.0.0
      - prompt-toolkit==3.0.48
      - protobuf==4.24.4
      - psutil==5.9.3
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pycparser==2.21
      - pygments==2.17.2
      - pyparsing==3.1.4
      - python-dateutil==2.9.0
      - python-slugify==8.0.4
      - pytorch-ignite==0.3.0
      - pytz==2024.2
      - pyyaml==6.0.1
      - pyzmq==24.0.1
      - regex==2024.4.16
      - requests==2.31.0
      - resampy==0.3.1
      - scikit-learn==0.22.1
      - scipy==1.4.1
      - sentry-sdk==2.17.0
      - setproctitle==1.3.3
      - setuptools==69.0.3
      - simplejpeg==1.7.3
      - six==1.16.0
      - smmap==5.0.1
      - soundfile==0.12.1
      - stack-data==0.6.2
      - termcolor==1.1.0
      - text-unidecode==1.3
      - torch==1.13.1
      - torchaudio==0.13.1
      - torchfile==0.1.0
      - torchvision==0.14.1
      - tornado==6.2
      - tqdm==4.43.0
      - traitlets==5.9.0
      - typing-extensions==4.7.1
      - urllib3==2.0.7
      - visdom==0.1.8.9
      - wandb==0.18.5
      - wcwidth==0.2.10
      - webencodings==0.5.1
      - websocket-client==1.6.1
      - wheel==0.42.0
      - widgetsnbextension==4.0.13
      - zipp==3.15.0
